### ISSUE TITLE
Error after latest update

### ISSUE THREAD

**Issue by JSandhu03** [kyrie25/spicetify-queue-panel#4] opened 2023-08-03 08:30 UTC
After the new update from August 2nd made to the extension, I've been getting the error "Something went wrong in Panel ID 4" which wasn't present in the previous version. 
Could I maybe get a copy of the older extension or maybe fix this error. This might be because I'm on an older version of spotify which might be removed for support after you updated the extension. 
Thanks a lot.

**Comment by kyrie25** [comment] 2023-08-03 08:34
Duplicate of #3

**Comment by kyrie25** [comment] 2023-08-03 08:35
The update doesn't change the behavior of the extension, it was a temporary patch for Spotify `1.2.17` as Spicetify has not been fully compatible with it.

**Closed as not planned by kyrie25** 2023-08-03 08:34 UTC

**Comment by kyrie25** [comment] 2023-08-03 08:35
You can either wait for Marketplace to update it, install the extension locally, wait for a Spicetify update or downgrade Spotify

**Comment by JSandhu03** [comment] 2023-08-03 08:39
I did install the extension locally from the github, and am on Spotify version 1.2.1.958.g6881e214. So what I should do is wait for a spicetify update right?

**Comment by kyrie25** [comment] 2023-08-03 08:44
That is severely outdated yes.
If you're claiming that an older version works for you then redownload this:
https://raw.githubusercontent.com/kyrie25/spicetify-queue-panel/e1ed5224927935fb45ce0637709d79fc31c1d865/queuePanel.js

Else you can wait for an update.

**Comment by JSandhu03** [comment] 2023-08-03 08:49
Yeah, I stopped updating as this version was the last one that didn't mess up a theme I use which wasn't being updated. 
But, thanks for the older version and yes, it started to work for me again after I changed the code :)
